version: '3.9'

services:
  backend: 
    build: 
      context: ./IGS-Employee-Manager
      dockerfile: Dockerfile

    ports:
      - '4040:4040'

    volumes:
      - ./IGS-Employee-Manager:/app/IGS
